name: receiptvault
description: AI-Powered Receipt Scanner & Expense Tracker
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core functionality
  camera: ^0.10.5
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.0.7
  image: ^4.1.3
  
  # State & Storage
  provider: ^6.1.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  
  # UI & Animations
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0
  lottie: ^3.0.0
  glass_kit: ^3.0.0
  
  # Charts & Analytics
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.1.41
  
  # Utilities
  intl: ^0.19.0
  http: ^1.1.2
  csv: ^6.0.0
  pdf: ^3.10.7
  share_plus: ^7.2.1
  
  # AI Integration
  google_generative_ai: ^0.2.0
  
  # iOS specific
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/animations/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700